### PR TITLE
Feature/set raise without delay

### PR DESCRIPTION
**Pull request by KennanChan**
- Modify the test command to prevent multiple instances of the same family from being saved to the same file path.
 - Add a guard to the idling event to prevent unnecessary calls to `SetRaiseWithoutDelay()`.

### CODE REVIEW

**Review by BobbyCJones — APPROVED** [review]

**Comment by KennanChan** [comment]
I will conduct additional tests on this change before it is merged.

**Comment by KennanChan** [comment]
> @KennanChan, I have tested on my machine and it is working very well. I will release our tools with this change for testing with some key users this week.

That's great because I haven't found a practical way to conduct thorough tests. Big thanks and waiting for good news!

**Comment by BobbyCJones** [comment]
@KennanChan We've been running your fix with the idling guard for over a month with 5 key users and we have not seen any issues.  It seems to be working great!

**Comment by KennanChan** [comment]
great, I'll review the code again and publish a new version as soon as possible

**Comment by KennanChan** [comment]
Hi, thanks a lot for your help. I have merged the PR and published a new nuget package.




Kennan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KennanChan/Revit.Async"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 晚上9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KennanChan/Revit.Async] Feature/set raise without delay (PR #26)





 
@KennanChan We've been running your fix with the idling guard for over a month with 5 key users and we have not seen any issues.  It seems to be working great!

**Comment by BobbyCJones** [comment]
Thank you @KennanChan!  This is a fantastic package that greatly reduces the complexity of coding in Revit.

**Comment by BobbyCJones** [comment]
FYI - It was working so well we expanded beyond the 5 key users and released to an entire department, about 30 users.  They run addins utilizing Revit.Async heavily...very heavily.  And it is running fantastic.  I'm updating our addins with the new package now.

**Pull request merged**
